#ifndef _ERRORS_H_
#define _ERRORS_H_

enum Errors{
    OK = 0,
    FIRING_UP_TIMEOUT,
    STABILIZATION_TIMEOUT,
    FUMES_TEMPERATURE_TOO_HIGH,
    FUMES_TEMPERATURE_TOO_LOW,
    CENTRAL_HEATING_TEMPERATURE_TO_HIGH
};

#endif